steps:
- task: DockerCompose@0
  displayName: Run python linting
  inputs:
    dockerComposeCommand: |
      run --rm python bash -c "pip install -e .[lint] && flake8"
- task: DockerCompose@0
  displayName: Run python tests
  inputs:
    dockerComposeCommand: |
      run --rm python bash -c "pip install -e .[test] && pytest \
                                                         --cov=pyspark_streaming_deployment \
                                                         --cov-report xml \
                                                         --cov-report html \
                                                         --junitxml /root/testresults.xml \
                                                         tests"
- task: PublishTestResults@2
  inputs:
    testResultsFiles: $(System.DefaultWorkingDirectory)/testresults.xml
- task: PublishCodeCoverageResults@1
  displayName: 'Publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
    reportDirectory: $(System.DefaultWorkingDirectory)/htmlcov
    failIfCoverageEmpty: true
