version: "3.3"
services:
  python:
    image: sdh-deployment
    build:
      context: ./
      dockerfile: Dockerfile_python
    working_dir: /root/
    privileged: true
    volumes:
     - type: bind
       source: ./
       target: /root
     - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
