version: "3.3"
services:
  python:
    image: python:3.7.0
    working_dir: /root/
    volumes:
    - type: bind
      source: ./
      target: /root
    tty: true
#    environment:
#      - ARTIFACT_STORE_USERNAME_E
#      - ARTIFACT_STORE_PASSWORD_E
#      - ARTIFACT_STORE_URL_E

  hadolint:
    image: hadolint/hadolint:latest-debian
    working_dir: /root/
    volumes:
    - type: bind
      source: ./
      target: /root
    tty: true
  dockerception:
    user: root
    image: dockerception
    build:
      context: ./
      dockerfile: Dockerfile_python
    working_dir: /root/
    privileged: true
    volumes:
     - type: bind
       source: ./
       target: /root
     - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
    environment:
      - REGISTRY_USERNAME
      - REGISTRY_PASSWORD
      - BUILD_SOURCEBRANCHNAME
      - BUILD_DEFINITIONNAME
      - ARTIFACT_STORE_USERNAME
      - ARTIFACT_STORE_PASSWORD
      - ARTIFACT_STORE_URL
