plugins:
  - takeoff_plugins

environment_keys:
  application_name: REPO_NAME
  branch_name: BRANCH_NAME

ci_environment_keys_acp:
  container_registry:
    username: REGISTRY_USER
    password: REGISTRY_PASSWORD
    registry: REGISTRY_SERVER

ci_environment_keys_prd:
  container_registry:
    username: REGISTRY_USER
    password: REGISTRY_PASSWORD
    registry: REGISTRY_SERVER
