version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  lint:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: python setup.py lint

  lint_yaml:
    docker:
      - image: giantswarm/yamllint:latest
    steps:
      - checkout
      - run: yamllint -d relaxed .

  lint_black:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install black
      - run: black -l 110 --check takeoff

  typecheck:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install mypy
      - run: python -m mypy --ignore-missing-imports -p takeoff

  test:
    docker:
      - image: schipholhub/takeoff-base:SNAPSHOT
    steps:
      - checkout
      - run: pip install -e .[test]
      - run: python setup.py test
      - codecov/upload

  takeoff_build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build -t takeoff:latest -f Dockerfile .

  takeoff:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: env | grep -v ^PATH > .env
      - run: docker build -t takeoff:latest -f Dockerfile .
      - run: docker run --env-file .env -v `echo $PWD`:/src -v /var/run/docker.sock:/var/run/docker.sock takeoff:latest takeoff

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - lint_yaml:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - lint_black:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - typecheck:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - test:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - takeoff_build:
          filters:
            branches:
              ignore: master
      - takeoff:
          requires:
            - lint
            - lint_yaml
            - lint_black
            - typecheck
            - test
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
