pool:
  vmImage: ubuntu-16.04

steps:
- script: docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${REGISTRY_LOGIN_SERVER}
  displayName: Login to registry

- task: DockerCompose@0
  displayName: Build Docker image and deploy on k8s
  inputs:
    dockerComposeCommand: |
      run --rm python runway
  env:
    AZURE_TENANTID: ${azure_tenantid}
    AZURE_KEYVAULT_SP_USERNAME_DEV: $(azure_keyvault_sp_username_dev)
    AZURE_KEYVAULT_SP_PASSWORD_DEV: $(azure_keyvault_sp_password_dev)
    AZURE_KEYVAULT_SP_USERNAME_ACP: $(azure_keyvault_sp_username_acp)
    AZURE_KEYVAULT_SP_PASSWORD_ACP: $(azure_keyvault_sp_password_acp)
    AZURE_KEYVAULT_SP_USERNAME_PRD: $(azure_keyvault_sp_username_prd)
    AZURE_KEYVAULT_SP_PASSWORD_PRD: $(azure_keyvault_sp_password_prd)
