version: "3.3"
services:
  pyspark:
    image: sdhcontainerregistryshared.azurecr.io/sdh-deployment:4.1.1-pyspark
    working_dir: /root/
    volumes:
    - type: bind
      source: ./
      target: /root
    tty: true
  python:
    image: sdhcontainerregistryshared.azurecr.io/sdh-deployment:4.1.1-python
    working_dir: /root/
    volumes:
    - type: bind
      source: ./
      target: /root
    tty: true
    environment:
    - BUILD_SOURCEBRANCHNAME
    - BUILD_DEFINITIONNAME
    - AZURE_TENANTID
    - AZURE_KEYVAULT_SP_USERNAME_DEV
    - AZURE_KEYVAULT_SP_PASSWORD_DEV
    - AZURE_KEYVAULT_SP_USERNAME_ACP
    - AZURE_KEYVAULT_SP_PASSWORD_ACP
    - AZURE_KEYVAULT_SP_USERNAME_PRD
    - AZURE_KEYVAULT_SP_PASSWORD_PRD
