name: Deploy

on:
  workflow_run:
    workflows: ["CI Build"]
    types: [completed]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Download Docker Image (Artifact)
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: path/to/artifacts
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Dockerhub
        run: |
          cd path/to/artifacts
          docker load < docker-image.tar
          export TAG=$(cat docker-tag)
          docker tag $TAG schipholhub/$TAG
          docker push schipholhub/$TAG
